app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),

    path('registro/', views.form_registro, name='form_registro'),
    path('registro_post/', views.registro, name='registro'),

    path('login/', views.form_login, name='form_login'),
    path('iniciar_sesion/', views.iniciar_sesion, name="iniciar_sesion"),
    path('logout/', views.cerrar_sesion, name='cerrar_sesion'),

    path('peliculas/', views.peliculas, name='peliculas'),
    path('peliculas/<int:id>/', views.pelicula, name='pelicula'),
    path('peliculas/crear/', views.form_crear_pelicula,
         name='form_crear_pelicula'),
    path('peliculas/crear_post/',
         views.crear_pelicula_post, name='crear_pelicula'),
    path('peliculas/eliminar/<int:id>/', views.eliminar_confirmacion,
         name="eliminar_confirmacion"),
    path('peliculas/eliminar_post/<int:id>/', views.eliminar_pelicula_post,
         name='eliminar_pelicula_post'),

    path('categorias/', views.categorias, name='categorias'),
    path('categorias/<int:id>/', views.categoria_view, name='categoria'),
    path('categorias/crear/', views.form_crear_categoria,
         name='form_crear_categoria'),
    path('categorias/crear_post/',
         views.crear_categoria_post, name='crear_categoria'),

    path('acerca/', views.acerca, name='acerca'),
]

blockbuster/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/models.py
from django.db import models


class Categoria(models.Model):
    nombre = models.CharField(max_length=100, null=False)
    descripcion = models.TextField(null=True)

    def __str__(self):
        return self.nombre

    class Meta:
        app_label = 'app'


class Director(models.Model):
    nombres = models.CharField(max_length=100, null=True)
    apellidos = models.CharField(max_length=100, null=True)
    nacionalidad = models.CharField(max_length=100, null=True)

    def __str__(self):
        return f'{self.nombres} {self.apellidos}'

    class Meta:
        app_label = 'app'


class Pelicula(models.Model):
    titulo = models.CharField(max_length=300, null=False)
    year = models.IntegerField(null=True)
    sinopsis = models.TextField(null=True)
    categoria = models.ForeignKey(
        Categoria,
        related_name='peliculas',
        null=False,
        on_delete=models.PROTECT
    )
    director = models.ForeignKey(
        Director,
        related_name='peliculas',
        null=True,
        on_delete=models.PROTECT
    )
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.titulo

    class Meta:
        app_label = 'app'

app/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404


from app.models import Categoria, Pelicula


def index(request):
    # return HttpResponse("Bienvenidos a BLOCKBUSTER")
    return render(request, 'app/index.html')


def peliculas(request):
    # Obtiene la lista de peliculas
    lista_peliculas = Pelicula.objects.all()
    # crear el contexto
    contexto = {
        'peliculas': lista_peliculas
    }
    return render(request, 'app/peliculas.html', contexto)


def pelicula(request, id):
    # Obtiene la pelicula
    pelicula = get_object_or_404(Pelicula, pk=id)
    contexto = {
        'pelicula': pelicula
    }
    return render(request, 'app/pelicula.html', contexto)


def acerca(request):
    return render(request, 'app/acerca.html')


def categorias(request):
    # Obtiene la lista de categorias
    lista_categorias = Categoria.objects.all()
    # Crea el contexto
    contexto = {
        'categorias': lista_categorias
    }
    return render(request, 'app/categorias.html', contexto)


def categoria_view(request, id):

    # Obtiene la categoria, y si no existe retorna erro 404
    categoria = get_object_or_404(Categoria, pk=id)

    # Obtiene la categoria
    #categoria = Categoria.objects.get(id=id)

    # Crea el contexto
    contexto = {
        'categoria': categoria
    }

    return render(request, 'app/categoria.html', contexto)


@login_required
def form_crear_categoria(request):
    return render(request, 'app/formCrearCategoria.html')


def crear_categoria_post(request):
    # Obtiene los datos de la categoría
    nombre = request.POST['nombre']
    descripcion = request.POST['descripcion']
    # Crea la categoría
    categoria = Categoria()
    categoria.nombre = nombre
    categoria.descripcion = descripcion
    # Guarda la categoria en la base de datos
    categoria.save()
    # Redirecciona a la página de categorías
    return redirect('app:categorias')


@login_required
def form_crear_pelicula(request):
    # Obtiene las categorías
    categorias = Categoria.objects.all()
    # Crea el contexto
    contexto = {
        'categorias': categorias
    }
    return render(request, 'app/formCrearPelicula.html', contexto)


def crear_pelicula_post(request):
    # Obtiene la información del formulario
    titulo = request.POST['titulo']
    id_categoria = int(request.POST['categoria'])
    year = int(request.POST['year'])

    # Obtiene la categoria
    categoria = Categoria.objects.get(id=id_categoria)

    # Crea la pelicula
    pelicula = Pelicula()
    pelicula.titulo = titulo
    pelicula.year = year
    pelicula.categoria = categoria

    # Guarda la pelicula en la BD
    pelicula.save()

    return redirect('app:peliculas')


def eliminar_confirmacion(request, id):
    # Obtiene la pelicula
    pelicula = Pelicula.objects.get(id=id)
    # Crea el contexto
    contexto = {
        'pelicula': pelicula
    }
    return render(request, 'app/eliminarPelicula.html', contexto)


def eliminar_pelicula_post(request, id):
    # Obtiene la pelicula por su id
    pelicula = Pelicula.objects.get(id=id)
    # Elimina la película
    pelicula.delete()
    return redirect('app:peliculas')


def form_registro(request):
    return render(request, 'app/registro.html')


def registro(request):
    # Obtiene los datos digitados en el formulario
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']

    # Crea el usuario
    usuario = User()
    usuario.username = username
    usuario.email = email
    usuario.set_password(password)

    # Guarda el usuario en la BD
    usuario.save()

    return redirect('app:index')


def form_login(request):
    return render(request, 'app/login.html')


def iniciar_sesion(request):
    # Obtiene los datops digitados por el usuario
    u = request.POST['username']
    p = request.POST['password']

    # Obtiene el usuario con el username y password
    usuario = authenticate(username=u, password=p)

    # Verifica que el usuario sea válido
    if usuario is not None:
        # Inicia la sesión del usuario
        login(request, usuario)
        # redirecciona al index
        return redirect('app:index')
    else:
        contexto = {
            'error': 'Credenciales no válidas'
        }
        return render(request, 'app/login.html', contexto)


def cerrar_sesion(request):
    # Cierra la sesión del usuario
    logout(request)

    # Redireccion al login
    return redirect('app:form_login')

app/templates/app/acerca.html
{% extends 'app/base.html' %}
{% load static %}

{% block titulo %}
Nosotros
{% endblock %}

{% block contenido %}
<h1>Nosotros</h1>
<h3>Desarrollado por John Cardozo</h3>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ab ipsa voluptatem, quod officiis placeat nisi quisquam
    cumque sequi corrupti, consectetur amet dicta dignissimos doloribus minus recusandae? Asperiores quam facilis
    distinctio!</p>

{% endblock %}

{% block estilos %}
<link rel="stylesheet" href="{% static 'app/css/acerca.css' %}">
{% endblock %}

app/templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block titulo %}
        Blockbuster
        {% endblock %}
    </title>
    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="{% static 'app/css/estilo.css' %}">
    {% block estilos %}
    {% endblock %}
</head>

<body>
    <header>
        <a href="{% url 'app:index' %}">
            <div class="logo">
                <div></div>
                <div>Blockbuster</div>
            </div>
        </a>
        <div>
            <span>
                {{ request.user.username }}
            </span>
            <a class="link-superior" href="{% url 'app:categorias' %}">Categorías</a>
            <a class="link-superior" href="{% url 'app:peliculas' %}">Películas</a>
            <a class="link-superior" href="{% url 'app:acerca' %}">Nosotros</a>

            {% if request.user.is_authenticated %}
            <a class="link-superior" href="{% url 'app:cerrar_sesion' %}">Salir</a>
            {% else %}
            <a class="link-superior" href="{% url 'app:form_login' %}">Ingresar</a>
            {% endif %}
        </div>
    </header>

    {% block contenido %}
    {% endblock %}

</body>

</html>

app/templates/app/categoria.html
{% extends "app/base.html" %}

{% block titulo %}
Pelicula
{% endblock %}

{% block contenido %}

<a href="{% url 'app:categorias' %}">Ir a categorias</a>

<h1>{{ categoria.nombre }}</h1>

<h2>Cantidad de peliculas: {{ categoria.peliculas.count }}</h2>

{% if categoria.peliculas.count > 0 %}
<table border="1">
    <thead>
        <tr>
            <th>Titulo</th>
            <th>Año</th>
        </tr>
    </thead>
    <tbody>
        {% for pelicula in categoria.peliculas.all %}
        <tr>
            <td>{{ pelicula.titulo }}</td>
            <td>{{ pelicula.year }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}

{% endblock %}

app/templates/app/categorias.html
{% extends "app/base.html" %}

{% block contenido %}
<h1>Categorías</h1>

{% if request.user.is_authenticated %}
<a href="{% url 'app:form_crear_categoria' %}">Crear categoría</a>
{% endif %}

<table border="1">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for categoria in categorias %}
        <tr>
            <td>{{ categoria.nombre }}</td>
            <td>
                {% if categoria.descripcion %}
                {{ categoria.descripcion }}
                {% endif %}
            </td>
            <td>
                <a href="{% url 'app:categoria' categoria.id %}">ver</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

{% block titulo %}
Categorias
{% endblock %}

app/templates/app/eliminarPelicula.html
{% extends 'app/base.html' %}
{% load static %}

{% block titulo %}
Eliminar pelicula
{% endblock %}

{% block contenido %}
<style>
    .acciones {
        display: flex;
        gap: 10px;
        margin: 15px;
    }

    .acciones a {
        padding: 5px 10px;
        border-radius: 8px;
        text-decoration: none;
    }

    .acciones a:nth-child(1) {
        color: #fff;
        background: #a40606;
    }

    .acciones a:nth-child(2) {
        background: #fff;
        color: #29298e;
        border: 1px solid #29298e;
    }
</style>
<h1><i class="far fa-trash-alt"></i> Eliminar película</h1>
<div>
    <h3>Está seguro de que desea eliminar la película "{{pelicula.titulo}}"?</h3>
    <div class="acciones">
        <a href="{% url 'app:eliminar_pelicula_post' pelicula.id %}">Sí</a>
        <a href="{% url 'app:peliculas' %}">No</a>
    </div>
</div>

{% endblock %}

app/templates/app/formCrearCategoria.html
{% extends "app/base.html" %}

{% block titulo %}
Crear categoría
{% endblock %}

{% block contenido %}
<h1>Crear categoría</h1>

<form action="{% url 'app:crear_categoria' %}" method="POST">
    {% csrf_token %}
    <label>Nombre</label>
    <input type="text" name="nombre">
    <br>
    <label>Descripción</label>
    <input type="text" name="descripcion">
    <br>
    <button>Crear categoría</button>
</form>

{% endblock %}

app/templates/app/formCrearPelicula.html
{% extends "app/base.html" %}

{% block titulo %}
Crear pelicula
{% endblock %}

{% block contenido %}
<h1>Crear película</h1>

<form action="{% url 'app:crear_pelicula' %}" method="POST">
    {% csrf_token %}
    <label>Título</label>
    <input type="text" name="titulo">
    <br>
    <label>Año</label>
    <input type="number" name="year">
    <br>
    <label>Categoría</label>
    <select name="categoria">
        {% for categoria in categorias %}
        <option value="{{categoria.id}}">{{categoria.nombre}}</option>
        {% endfor %}
    </select>
    <br>
    <button>Crear película</button>
</form>

{% endblock %}

app/templates/app/index.html
{% extends "app/base.html" %}

{% block contenido %}
<a href="{% url 'app:peliculas' %}">Ver todas las películas</a>
{% endblock %}

app/templates/app/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio</title>
    <link rel="stylesheet" href="{% static 'app/css/auth.css' %}">
</head>

<body>
    <div class="contenido">
        <div class="form-registro">
            <h2>Ingresar a Blockbuster</h2>
            <form action="{% url 'app:iniciar_sesion' %}" method="POST">
                {% csrf_token %}
                <fieldset>
                    <label>Username</label>
                    <input type="text" name="username">
                </fieldset>
                <fieldset>
                    <label>Password</label>
                    <input type="password" name="password">
                </fieldset>
                <button>Iniciar sesión</button>
                {% if error %}
                <span class="error">{{error}}</span>
                {% endif %}
            </form>
        </div>
    </div>
</body>

</html>

app/templates/app/pelicula.html
{% extends "app/base.html" %}

{% block contenido %}
{% if pelicula %}

<h1>{{ pelicula.titulo }}</h1>
<h2>Puntaje: {{ pelicula.puntaje }}</h2>
<p>{{ pelicula.descripcion }}</p>

{% else %}

<h1>Error 404!! 😭</h1>
<h3>La película que desea ver no existe!</h3>

{% endif %}

{% endblock %}

{% block titulo %}

{% if pelicula %}
{{ pelicula.titulo }}
{% else %}
Error
{% endif %}

{% endblock %}

app/templates/app/peliculas.html
{% extends "app/base.html" %}

{% block contenido %}
<style>
    table,
    td,
    th {
        border: 1px solid #000;
        border-collapse: collapse;
    }

    td,
    th {
        padding: 5px;
    }

    th {
        background: orange;
        color: #000;
    }

    .no-disponible {
        font-family: Arial, Helvetica, sans-serif;
        font-size: 0.7em;
        padding: 2px 7px;
        background: #066ba2;
        color: #fff;
        border-radius: 5px;
    }
</style>
</head>

<h1><i class="fas fa-film"></i> Peliculas</h1>

<a href="{% url 'app:form_crear_pelicula' %}">Crear película</a>

{% if peliculas %}
<table>
    <tr>
        <th>Titulo</th>
        <th>Año</th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    {% for pelicula in peliculas %}
    <tr>
        <td>{{ pelicula.titulo }}</td>
        <td>
            {% if pelicula.year %}
            {{ pelicula.year }}
            {% else %}
            <span class="no-disponible">No disponible</span>
            {% endif %}
        </td>
        <td>
            <a href="{% url 'app:pelicula' pelicula.id %}" title="Ver pelicula" class="link-ver">
                <i class="fas fa-search"></i>
            </a>
        </td>
        <td>
            <a href="#" title="Editar película" class="link-editar">
                <i class="fas fa-pencil-alt"></i>
            </a>
        </td>
        <td>
            <a href="{% url 'app:eliminar_confirmacion' pelicula.id %}" title="Eliminar película" class="link-borrar">
                <i class="far fa-trash-alt"></i>
            </a>
        </td>
    </tr>
    {% endfor %}
</table>
{% else %}
<h1>No hay peliculas disponibles</h1>
{% endif %}

{% endblock %}

{% block titulo %}
Películas
{% endblock %}

app/templates/app/registro.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio</title>
    <link rel="stylesheet" href="{% static 'app/css/auth.css' %}">
</head>

<body>
    <div class="contenido">
        <div class="form-registro">
            <h2>Crear cuenta</h2>
            <form action="{% url 'app:registro' %}" method="POST">
                {% csrf_token %}
                <fieldset>
                    <label>Username</label>
                    <input type="text" name="username">
                </fieldset>
                <fieldset>
                    <label>Email</label>
                    <input type="email" name="email">
                </fieldset>
                <fieldset>
                    <label>Password</label>
                    <input type="password" name="password">
                </fieldset>
                <button>Crear cuenta</button>
            </form>
        </div>
    </div>
</body>

</html>